### ISSUE TITLE
Refactor /tables API to always use "name" instead of "tableName"

### ISSUE THREAD

**Issue by Narigo** [campudus/tableaux#28]
We should refactor the API that it always uses "name" instead of "tableName". When doing `GET /tables`, we get `{ "id" : 1, "name" : "test" }`.

**Comment by Narigo** [comment]
Same with `tableId` -> `id`

**Comment by alexvetter** [comment]
No, problem. But why? Backbone?

**Comment by Narigo** [comment]
Consistency ;)
And yes, it will be easier to use in Backbone (and everything else) later
Am 13.05.2015 19:42 schrieb "Alexander Vetter" <notifications@github.com>:
