### ISSUE TITLE
Feature – Media Management

### ISSUE THREAD

**Issue by alexvetter** [campudus/tableaux#40]
# Folders

**`GET /folders/:id`** :white_check_mark:

Get folder with all containing sub-folders and files

```json
{
  "id":2,
  "name":"Downloads",
  "description":"Alle Downloads",
  "parent":null,
  "subfolders":[
    {
      "id":3,
      "name":"Videos",
      "description":"Alle Videos",
      "parent":2
    }
  ],
  "files":[
    {
      "..."
    }
  ]
}
```

**`POST /folders`** or **`PUT /folders/:id`** :white_check_mark:

Create or change a folder

```json
{
  "name": "Videos",
  "description": "Alle Downloads",
  "parent": 2
}
```

**`DELETE /folders/:id`** :white_check_mark:

Deletes folder, subfolder and all files in that hierarchy – without a warning!

```
{
  "id":2,
  "name":"Downloads",
  "description":"Alle Downloads",
  "parent":null
}
```
# Files

**`GET /files/:uuid`** :white_check_mark:

Get meta-information about a file

```json
{
  "uuid": "e87fdf87-ce60-4ae7-9293-32c616d4bd60",
  "name": "Lustiges Video",
  "description": "Ein lustiges Video mit schönen Inhalt.",
  "folder": 3,
  "mimeType": "video/mpeg2",
  "createdAt": "2015-03-02 13:30",
  "updatedAt": "2015-03-02 13:30",
  "url": "/files/e87fdf87-ce60-4ae7-9293-32c616d4bd60/Lustiges%20Video.mpg"
}
```

**`GET /files/:uuid/pseudo.jpg`** :white_check_mark:

Get raw file

```
raw file
```

**`POST /files`** :white_check_mark:

Creates new temporary file. Returns `uuid` of temporary uploaded file.

```json
{
  "uuid": "fc56f278-9f63-4135-a2cd-b39ceba02c5c"
}
```

**`PUT /files/:uuid`** :white_check_mark:

Persists temporary file.

```json
{
  "name": "Lustiges Video",
  "description": "Ein lustiges Video mit schönen Inhalt.",
  "folder": 3,
  "mimeType": "video/mpeg2"
}
```

**Comment by Narigo** [comment]
Should be done with merged PR, I guess.
