### ISSUE TITLE
Get values of specific column

### ISSUE THREAD

**Issue by Narigo** [campudus/tableaux#41]
A `GET /tables/2/columns/2/rows` that lists the values of that column would be nice to use in links. It would make sense to have the id of the row, too, so a result like the following example could make sense:

```
{
  "column" : {
    "id": 2,
    "name": "Hauptstadt",
    "kind": "text",
    "ordering": 2
  },
  rows : [
    { "id" : 1, "value" : "München" },
    { "id" : 2, "value" : "Landshut" },
    { "id" : 3, "value" : "Regensburg" },
    { "id" : 4, "value" : "Bayreuth" },
    { "id" : 5, "value" : "Tübingen" },
    { "id" : 6, "value" : "Karlsruhe" },
    { "id" : 7, "value" : "Stuttgart" },
    { "id" : 8, "value" : "Freiburg" },
  ]
}
```

I know this is not consistent with the other queries (no "columns" list, but a single "column" object). I'll open another issue for that.

**Comment by alexvetter** [comment]
Do to easier integration JSON looks like below. The information about the column will not be included because it should be known prior to this request.

```json
{
  "status": "ok",
  "page": {
    "offset": null,
    "limit": null,
    "totalSize": 16
  },
  "rows": [
    {
      "id": 3,
      "values": [
        "a"
      ]
    },
    {
      "id": 4,
      "values": [
        "b"
      ]
    },
    {
      "id": 5,
      "values": [
        "c"
      ]
    }
  ]
}
```
