### ISSUE TITLE
Change API and get rid of JSON redundacy

### ISSUE THREAD

**Issue by Narigo** [campudus/tableaux#42]
We should talk about whether we want to be consistent or change the way we work with the API. We won't need to change the `GET /tables/1` case that catches all information about a table, but `POST` and `PUT` may change. As we only use `GET /tables/1` all right now, it might be a good idea to do that now.

Right now, when changing a cell, we do a request something like this:

```
PUT /tables/1/columns/1/rows/1
{
  "cells" : [ {
    "value": "Something"
  } ]
}
```

It would make sense to just do this:
```
PUT /tables/1/columns/1/rows/1
{
  "value": "Something"
}
```

**Comment by alexvetter** [comment]
closed by fixing #36
