### ISSUE TITLE
Simplify adding link values

### ISSUE THREAD

**Issue by Narigo** [campudus/tableaux#44]
Currently we send `{ "value" : [<fromRowId>, <toRowId>] }` to add a new link.

It would make sense to a change this from JsonArray to a JsonObject with `from` and `to` fields.

```json
{
  "value": {
    "from": <fromRowId>,
    "to": <toRowId>
  }
}
```

**Comment by alexvetter** [comment]
With c6dcd75 Joern changed the behavior. Now there are two ways:

### 1. Overwrite all links values
In this case all current values will be deleted and 

```json
{
  "value": {
    "from": <fromRowId>,
    "values": [
      <toRowId>,
      <toRowId>,
      <toRowId>
    ]
  }
}
```

### 2. Add link value
In this case a link value will be added to the current values.

```json
{
  "value": {
    "from": <fromRowId>,
    "to": <toRowId>
  }
}
```
